version: 0.1

phases:
  install:
    commands:
      - apt-get update
      - apt-get install -y python-setuptools python-pip python-dev build-essential 
      - pip install awscli
  pre_build:
    commands:
      - echo Setting up for a build.
  build:
    commands:
      - echo Build started on `date`
      - npm install          
      - npm run build
  post_build:
    commands:
      - echo Build completed on `date`
      - aws s3 sync ./dist/* s3://docs.mshanken.io/
